function g_strcts = loadKofikoStructs(mainKofiko_fname)

g_strcts = load(mainKofiko_fname, 'g_strctDAQParams', ...
    'g_astrctAllParadigms', 'g_strctLog', 'g_strctEyeCalib', ...
    'g_strctAppConfig', 'g_strctSharedParadigmData', ...
    'g_strctStimulusServer', 'g_strctSystemCodes');
end